/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myboggle;

import java.awt.Graphics;

/**
 *
 * @author agung
 */
public class JFMain extends javax.swing.JFrame {

    /**
     * Creates new form JFMain
     */
    public JFMain() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewGame = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        btnReset = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtWords = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JToggleButton();
        b2 = new javax.swing.JToggleButton();
        b3 = new javax.swing.JToggleButton();
        b4 = new javax.swing.JToggleButton();
        b5 = new javax.swing.JToggleButton();
        b6 = new javax.swing.JToggleButton();
        b7 = new javax.swing.JToggleButton();
        b8 = new javax.swing.JToggleButton();
        b9 = new javax.swing.JToggleButton();
        b10 = new javax.swing.JToggleButton();
        b11 = new javax.swing.JToggleButton();
        b12 = new javax.swing.JToggleButton();
        b13 = new javax.swing.JToggleButton();
        b14 = new javax.swing.JToggleButton();
        b15 = new javax.swing.JToggleButton();
        b16 = new javax.swing.JToggleButton();
        b17 = new javax.swing.JToggleButton();
        b18 = new javax.swing.JToggleButton();
        b19 = new javax.swing.JToggleButton();
        b20 = new javax.swing.JToggleButton();
        b21 = new javax.swing.JToggleButton();
        b22 = new javax.swing.JToggleButton();
        b23 = new javax.swing.JToggleButton();
        b24 = new javax.swing.JToggleButton();
        b25 = new javax.swing.JToggleButton();
        paused = new javax.swing.JLabel();
        loadingtable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FindWord 1.0");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myboggle/resources/rst.png"))); // NOI18N
        btnNewGame.setBorder(null);
        btnNewGame.setBorderPainted(false);
        btnNewGame.setDefaultCapable(false);
        btnNewGame.setFocusPainted(false);
        btnNewGame.setFocusable(false);
        getContentPane().add(btnNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 60, 60));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myboggle/resources/pause.png"))); // NOI18N
        jToggleButton2.setBorder(null);
        jToggleButton2.setBorderPainted(false);
        jToggleButton2.setFocusPainted(false);
        jToggleButton2.setFocusable(false);
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 60, 60));

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myboggle/resources/no.png"))); // NOI18N
        btnReset.setBorder(null);
        btnReset.setBorderPainted(false);
        btnReset.setFocusable(false);
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 50, 50));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myboggle/resources/yes.png"))); // NOI18N
        btnSubmit.setBorder(null);
        btnSubmit.setBorderPainted(false);
        btnSubmit.setFocusable(false);
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 50, 50));

        jLabel3.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("999");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 150, 40));

        txtWords.setFont(new java.awt.Font("Dimbo", 1, 24)); // NOI18N
        txtWords.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtWords.setText("?");
        txtWords.setToolTipText("");
        getContentPane().add(txtWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 419, 270, 40));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Word(s) List"));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "About" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setFocusable(false);
        jList1.setRequestFocusEnabled(false);
        jList1.setVerifyInputWhenFocusTarget(false);
        jList1.setVisibleRowCount(10);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 190, 230));

        jPanel1.setLayout(new java.awt.GridLayout(5, 5, 5, 5));

        b1.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b1.setText("?");
        b1.setFocusPainted(false);
        b1.setFocusable(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);

        b2.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b2.setText("?");
        b2.setFocusPainted(false);
        b2.setFocusable(false);
        jPanel1.add(b2);

        b3.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b3.setText("?");
        b3.setFocusPainted(false);
        b3.setFocusable(false);
        jPanel1.add(b3);

        b4.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b4.setText("?");
        b4.setFocusPainted(false);
        b4.setFocusable(false);
        jPanel1.add(b4);

        b5.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b5.setText("?");
        b5.setFocusPainted(false);
        b5.setFocusable(false);
        jPanel1.add(b5);

        b6.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b6.setText("?");
        b6.setFocusPainted(false);
        b6.setFocusable(false);
        jPanel1.add(b6);

        b7.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b7.setText("?");
        b7.setFocusPainted(false);
        b7.setFocusable(false);
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);

        b8.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b8.setText("?");
        b8.setFocusPainted(false);
        b8.setFocusable(false);
        jPanel1.add(b8);

        b9.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b9.setText("?");
        b9.setFocusPainted(false);
        b9.setFocusable(false);
        jPanel1.add(b9);

        b10.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b10.setText("?");
        b10.setFocusPainted(false);
        b10.setFocusable(false);
        jPanel1.add(b10);

        b11.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b11.setText("?");
        b11.setFocusPainted(false);
        b11.setFocusable(false);
        jPanel1.add(b11);

        b12.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b12.setText("?");
        b12.setFocusPainted(false);
        b12.setFocusable(false);
        jPanel1.add(b12);

        b13.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b13.setText("?");
        b13.setFocusPainted(false);
        b13.setFocusable(false);
        jPanel1.add(b13);

        b14.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b14.setText("?");
        b14.setFocusPainted(false);
        b14.setFocusable(false);
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        jPanel1.add(b14);

        b15.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b15.setText("?");
        b15.setFocusPainted(false);
        b15.setFocusable(false);
        jPanel1.add(b15);

        b16.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b16.setText("?");
        b16.setFocusPainted(false);
        b16.setFocusable(false);
        jPanel1.add(b16);

        b17.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b17.setText("?");
        b17.setFocusPainted(false);
        b17.setFocusable(false);
        jPanel1.add(b17);

        b18.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b18.setText("?");
        b18.setFocusPainted(false);
        b18.setFocusable(false);
        jPanel1.add(b18);

        b19.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b19.setText("?");
        b19.setFocusPainted(false);
        b19.setFocusable(false);
        jPanel1.add(b19);

        b20.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b20.setText("?");
        b20.setFocusPainted(false);
        b20.setFocusable(false);
        jPanel1.add(b20);

        b21.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b21.setText("?");
        b21.setFocusPainted(false);
        b21.setFocusable(false);
        jPanel1.add(b21);

        b22.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b22.setText("?");
        b22.setFocusPainted(false);
        b22.setFocusable(false);
        jPanel1.add(b22);

        b23.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b23.setText("?");
        b23.setFocusPainted(false);
        b23.setFocusable(false);
        jPanel1.add(b23);

        b24.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b24.setText("?");
        b24.setFocusPainted(false);
        b24.setFocusable(false);
        jPanel1.add(b24);

        b25.setFont(new java.awt.Font("Dimbo", 1, 28)); // NOI18N
        b25.setText("?");
        b25.setFocusPainted(false);
        b25.setFocusable(false);
        jPanel1.add(b25);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 360, 360));

        paused.setFont(new java.awt.Font("Dimbo", 1, 48)); // NOI18N
        paused.setText("PAUSED!");
        getContentPane().add(paused, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        loadingtable.setFont(new java.awt.Font("Dimbo", 1, 48)); // NOI18N
        loadingtable.setText("Loading table...");
        getContentPane().add(loadingtable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myboggle/backdrop.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton b1;
    public javax.swing.JToggleButton b10;
    public javax.swing.JToggleButton b11;
    public javax.swing.JToggleButton b12;
    public javax.swing.JToggleButton b13;
    public javax.swing.JToggleButton b14;
    public javax.swing.JToggleButton b15;
    public javax.swing.JToggleButton b16;
    public javax.swing.JToggleButton b17;
    public javax.swing.JToggleButton b18;
    public javax.swing.JToggleButton b19;
    public javax.swing.JToggleButton b2;
    public javax.swing.JToggleButton b20;
    public javax.swing.JToggleButton b21;
    public javax.swing.JToggleButton b22;
    public javax.swing.JToggleButton b23;
    public javax.swing.JToggleButton b24;
    public javax.swing.JToggleButton b25;
    public javax.swing.JToggleButton b3;
    public javax.swing.JToggleButton b4;
    public javax.swing.JToggleButton b5;
    public javax.swing.JToggleButton b6;
    public javax.swing.JToggleButton b7;
    public javax.swing.JToggleButton b8;
    public javax.swing.JToggleButton b9;
    public javax.swing.JButton btnNewGame;
    public javax.swing.JButton btnReset;
    public javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JList<String> jList1;
    public javax.swing.JList<String> jList2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JToggleButton jToggleButton2;
    public javax.swing.JLabel loadingtable;
    public javax.swing.JLabel paused;
    public javax.swing.JLabel txtWords;
    // End of variables declaration//GEN-END:variables
}
